### ISSUE TITLE
Inconsistent behavior when response status codes are changed

### ISSUE THREAD

**Issue by ciprian-tibulca** [oasdiff/oasdiff#194]
**Describe the bug**
Changing a response code from 4xx to 5xx is handled differently by `-breaking-only` and `-check-breaking` flags:
- `-breaking-only` considers it as a breaking change, reporting the removal of 4xx 
- `-check-breaking` considers it as a non-breaking change. Here only the removal of 2xx codes is considered breaking (ResponseSuccessStatusRemoved checker).

**To Reproduce**
Given specs:
1. `base.yaml`:
```
openapi: 3.0.1
info:
  title: Test API
paths:
  /api/changeOfStatusCodesTest:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Bad request.
          content:
            application/json:
              schema:
                type: string
```
2. `revision.yaml`
```
openapi: 3.0.1
info:
  title: Test API
paths:
  /api/changeOfStatusCodesTest:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Internal server error.
          content:
            application/json:
              schema:
                type: string
```

1. Run `oasdiff -base base.yaml -revision revision.yaml  -breaking-only -format yaml`
4. Recieve:
```
paths:
    modified:
        /api/atlas/v2/changeOfStatusCodesTest:
            operations:
                modified:
                    GET:
                        responses:
                            deleted:
                                - "400"
```                               
3. Run `oasdiff -base base.yaml -revision revision.yaml  -check-breaking -format text`
4. Recieve: no output (no breaking change detected)

**Expected behavior**
`-check-breaking` should consider the removal of any response status code (not only 2xx) as a breaking change.

**Desktop (please complete the following information):**
 - OS: macOS Ventura

**Describe alternatives you've considered**
one option I would be willing to work on is to add 2 new args `-include-checks` and `-exclude-checks` that will give us the ability to customize breaking changes default profile.
`oasdiff -base base.yaml -revision revision.yaml  -check-breaking -include-checks  response-status-code-removed -format text`

**Comment by reuvenharrison** [comment]
First, `-breaking-only` and `-check-breaking` are not designed to be consistent.
`-check-breaking` has a better set of tests and should be preferred over `-breaking-only`.

Secondly, I'm not sure whether removal of non-2xx responses should be considered a breaking-change or not.
Could you please give an example that shows how a client breaks because of this kind of change (removing a 4xx or 5xx response)?

@derbylock what is your take on this?

**Comment by ciprian-tibulca** [comment]
Customers might have recovery flows that will be affected (/ inactivated) by the removal of error response codes, e.g. 409 Conflict, 408 Request Timeout.
Also, it's a way to avoid centralizing error codes (e.g. 400, 408, 409 -> 500).

Even though it's not a strong opinion, I'd say in general that the removal of features / flags / fields that are not explicitly defined as optional can be considered a breaking change.

**Comment by derbylock** [comment]
From my point of view, removal of any status codes except successful is not breaking. Firstly, if clients have specific logic for some statuses you've removed, it doesn't break them. You've removed status, so you won't send them and logic related to them in clients simply won't work. Secondly, as API based on HTTP, all non-success status codes can be received by clients, even if they aren't declared in openapi specification. E.g. some Middleware (nginx, envoy, service mesh, hardware balancers, api gateways,  etc.) can send any status because of its internal logic. In most cases it is bad idea to describe statuses usually used by infrastructure.

Anyway, if you want to disallow any status codes removal for -check-breaking, it could be made by adding custom check.

I agree with idea of adding/ removing checks by its ids via command line. It is the one task in my list of improvements. But I've no enough time atm to do it.

**Comment by reuvenharrison** [comment]
Thanks @tibulca and @derbylock.
Let's proceed with the ability to customize checks.

**Comment by reuvenharrison** [comment]
Fixed by https://github.com/Tufin/oasdiff/pull/195

**Comment by reuvenharrison** [comment]
see https://github.com/Tufin/oasdiff#optional-backwards-compatibility-checks

**Comment by ciprian-tibulca** [comment]
Thanks a lot @reuvenharrison for the quick fix and release!
