### ISSUE TITLE
What happened to v2 tags in docker hub?

### ISSUE THREAD

**Issue by aghajani** [oasdiff/oasdiff#324]
It seems after [v1.6.1](https://github.com/Tufin/oasdiff/releases/tag/v1.6.1) release (or v1.6.0), all docker image tags with v2 are removed, so suddenly our image ref `tufin/oasdiff:v2.0.1` is not valid anymore

**Comment by reuvenharrison** [comment]
Hi @aghajani 
We decided to abandon v2 due to golang complexities (see [discussion](https://github.com/Tufin/oasdiff/discussions/319) and [issue](https://github.com/Tufin/oasdiff/issues/318) for more info).
We're back on the v1 track now and [v1.6.1](https://github.com/Tufin/oasdiff/releases/tag/v1.6.1) is the latest release.
Sorry about the confusion.
Reuven

**Comment by reuvenharrison** [comment]
By the way, `docker pull tufin/oasdiff:stable` should always give you the latest stable version.

**Comment by aghajani** [comment]
Thanks for the update, I could guess and already adjusted our system to use the v1.6.1, but as a general note, deleting tags is not a good practice since many pipelines and tools are using pinned versions/tags for good reasons and a change/decision like that can easily break them all. The releases are supposed to be immutable ;)
