### ISSUE TITLE
Tool does not recognise enum item removal as breaking change

### ISSUE THREAD

**Issue by milan-vondra** [oasdiff/oasdiff#639]
**Describe the bug**
Tool does not recognise enum item removal as breaking change

**To Reproduce**
Steps to reproduce the behaviour:
1. The command-line, for example: `oasdiff breaking spec1.yaml spec2.yaml `
2. source spec with a field
        severityType:
          type: string
          enum: [NORMAL, CRITICAL]
3. update spec with a field
        severityType:
          type: string
          enum: [NORMAL, BREAKING]
4. Output is empty
warning	[response-property-enum-value-added] at enum_item_removed_breaking.yaml
	in API GET /severityTypes
		added the new 'BREAKING' enum value to the '/items/severityType' response property for the response status '200'
		Adding new enum values to response could be unexpected for clients, use x-extensible-enum instead.

**Expected behavior**
This should have been detected as breaking change

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS 15.2

**Comment by reuvenharrison** [comment]
Hi @milan-vondra 
I usually insist on full examples to avoid misunderstandings but I'll do my best to address this based on the partial info given above.

First thing to note is that this is in the **response**, not in the **request** which would behave differently.
Deleting an enum value from the **response** should not affect the client, that value will just never be received again.

Also, if you use the `changeling` command instead of `breaking`, you will get an INFO-level alert about this change:
`oasdiff changelog spec1.yaml spec2.yaml`

**Comment by milan-vondra** [comment]
Oh, this is my bad, the enum was not used in request. Sorry for the confusion.

**Comment by milan-vondra** [comment]
Oh, this is my bad, the enum was not used in request. Sorry for the confusion.
