### ISSUE TITLE
Tool does not recognise when a new field is added to the request as breaking change

### ISSUE THREAD

**Issue by milan-vondra** [oasdiff/oasdiff#640]
**Describe the bug**
Tool does not recognise when a new field is added to the request as breaking change

**Actual behavior**
There is no output at all

**Expected behavior**
This should have been detected as breaking change

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS 15.2

**Comment by reuvenharrison** [comment]
Please provide full specs and command-line otherwise I don't know which case you are referring to exactly.

**Comment by milan-vondra** [comment]
OK, here is a minimalistic version of the spec
Steps:
1. extract zip 
2. in the folder with spec files run oasdiff:
`oasdiff breaking ./minimalistic_request_openapi.yaml ./breaking_change_add_request_field.yaml`

[spec_sample.zip](https://github.com/user-attachments/files/18179617/spec_sample.zip)
Expected:
Detect breaking change in request - adding new field

Actual:
Output is empty

**Comment by reuvenharrison** [comment]
Thanks for the additional details.

This is detected as an INFO-level change since the new field is **optional**.
You can see it by running:
`oasdiff changelog ./minimalistic_request_openapi.yaml ./breaking_change_add_request_field.yaml`

If the field would have been **required**, it would be considered a breaking change.

For reference: https://swagger.io/docs/specification/v3_0/describing-parameters/#required-and-optional-parameters
