### ISSUE TITLE
Add support for OpenAPI custom extensions

### ISSUE THREAD

**Issue by petkostas** [oasdiff/oasdiff#89]
**Is your feature request related to a problem? Please describe.**
Some of our OpenAPI specifications are new and under development, it becomes difficult to exclude them from automating backward compatibility checks (as they will often fail due to changes).

**Describe the solution you'd like**
Add support for filtering based on OpenAPI custom extensions (e.g. `-exclude-extension x-beta`)

**Describe alternatives you've considered**

- Manual script parsing schemas and comparing against oasdiff
- Enabling manually oasdiff for specific APIs (increases maintenance, defies automation).

**Additional context**

**Comment by reuvenharrison** [comment]
Hi @petkostas,
Thanks for submitting this issue.
Before adding another configuration flag to support your request, I'd like to suggest using the [Operation Tag](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#fixed-fields-8) instead of [Specification Extensions](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#specification-extensions) to document your APIs.
What do you think?

**Comment by petkostas** [comment]
Hi @reuvenharrison thanks for the suggestion, we do use the operation tags, but there are also some tools that add custom specification extensions.
Obviously, the exclude filter could take into consideration tags, the suggestion for the extension was mostly based on the fact that some other OSS tools make use of it.
In our case, the operation tag would be also a perfect candidate!

**Comment by reuvenharrison** [comment]
I have two follow up questions:
1. Can you provide an example of an OSS tool that uses extensions? I'd like to make sure that I understand this.
2. What happens if an API has an 'x-beta' extension in one of the specs only? For example:

Spec 1:
```yaml
info:
  title: Tufin
  version: 1.0.0
openapi: 3.0.3
paths:
  /api/test:
    x-beta: true 
    get:
      responses:
        200:
          description: OK
``` 

Spec 2:
```yaml
info:
  title: Tufin
  version: 1.0.0
openapi: 3.0.3
paths:
  /api/test:
    get:
      responses:
        200:
          description: OK
``` 

what should be the results of:
`oasdiff -base spec1 -revision spec2`
and:
`oasdiff -base spec2 -revision spec1`

**Comment by petkostas** [comment]
@reuvenharrison examples of using extensions:
- https://redocly.com/docs/cli/guides/hide-apis/
- Stoplight also uses an `x-private` extension

We are not currently using an extension to mark APIs as beta (and as you mentioned we can easily also use a tag for it), to help you understand more, we use oasdiff in our repository pipelines. every MR checks for changes against the master repo reference.
For the moment as we can't support tags or extensions, we have to manually specify which APIs are stable and additionally the ones under development. In case there is a change of the APIs under development oasdiff needs to be completely bypassed by using a commit-specific title.
I hope this makes it a bit more clear.
In your example, oasdiff would completely ignore the specific path when comparing it.
